export enum ActionsType {
  UP_PARAMETER = "UP_PARAMETER",
  DOWN_PARAMETER = "DOWN_PARAMETER",
  LVLUP_SKILL = "LVLUP_SKILL",
  UPLOAD_CHARACTER = "UPLOAD_CHARACTER",
  CHANGE_NAME = "CHANGE_NAME",
  GET_DAMAGE = "GET_DAMAGE",
}
